Problem: images are created as root/root
... thus qemu as teto/users can't read them.

I think that's where it's uploaded with wrong rights

    def _upload_volume(self, filename, actual_size):
        stream = self.conn.newStream()
        self.vol.upload(stream, offset=0, length=actual_size)

main> building '/nix/store/4z0gk8yiqj8983x2gsjkrpbbaqbypq2x-libvirtd-ssh-image.drv'...
main> Formatting '/nix/store/55wbixc0qg5rfbgvlyz6zh7278xa24i5-libvirtd-ssh-image/image', fmt=qcow2 size=12884901888 backing_file=/nix/store/rv7558jd2q14vchzzsmqsak8z5w53v5c-libvirtd-image/disk.qcow2 cluster_size=65536 lazy_refcounts=off refcount_bits=16

main>
main> iPXE (http://ipxe.org) 00:03.0 C980 PCI2.10 PnP PMM+2FF913A0+2FEF13A0 C980
main>
main>
main>
main> Booting from ROM...
main> Probing EDD (edd=off to disable)... ocloading kernel modules...
main> insmod: can't insert '/nix/store/b0g2qpzfv8g1b90hj0r23lc84ryjp97a-linux-4.14.63-shrunk/lib/modules/4.14.63/kernel/arch/x86/crypto/crc32c-intel.ko.xz': No such device
main> warning: unable to load /nix/store/b0g2qpzfv8g1b90hj0r23lc84ryjp97a-linux-4.14.63-shrunk/lib/modules/4.14.63/kernel/arch/x86/crypto/crc32c-intel.ko.xz
main> mounting Nix store...
main> mounting host's temporary directory...
main> starting stage 2 (/nix/store/6j3r6wxvgsg9mc5a7x6nrqwm8kn28wmx-vm-run-stage2)
main> [    0.784984] reboot: Power down
main> uploading disk image...
main> defining xml...
main> starting 2...
isRunning
isActive
main> starting...
libvirt: QEMU Driver error : internal error: process exited while connecting to monitor: 2018-08-20T06:15:00.830835Z qemu-system-x86_64: -drive file=/var/lib/libvirt/images/nixops-0f3af861-a440-11e8-8798-309c233b770e-main.qcow2,format=qcow2,if=none,id=drive-ide0-0-0: Could not open '/var/lib/libvirt/images/nixops-0f3af861-a440-11e8-8798-309c233b770e-main.qcow2': Permission denied
Traceback (most recent call last):
  File "/home/teto/nixops/scripts/nixops", line 984, in <module>
    args.op()
  File "/home/teto/nixops/scripts/nixops", line 406, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/home/teto/nixops/nixops/deployment.py", line 1056, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/home/teto/nixops/nixops/deployment.py", line 1045, in run_with_notify
    f()
  File "/home/teto/nixops/nixops/deployment.py", line 1056, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/home/teto/nixops/nixops/deployment.py", line 989, in _deploy
    nixops.parallel.run_tasks(nr_workers=-1, tasks=self.active_resources.itervalues(), worker_fun=worker)
  File "/home/teto/nixops/nixops/parallel.py", line 44, in thread_fun
    result_queue.put((worker_fun(t), None, t.name))
  File "/home/teto/nixops/nixops/deployment.py", line 962, in worker
    r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
  File "/home/teto/nixops/nixops/backends/libvirtd.py", line 205, in create
    self.start()
  File "/home/teto/nixops/nixops/backends/libvirtd.py", line 398, in start
    self.dom.create()
  File "/nix/store/016sfszbxd194isl14z64qgh90dh7gs2-python2.7-libvirt-4.6.0/lib/python2.7/site-packages/libvirt.py", line 1080, in create
    if ret == -1: raise libvirtError ('virDomainCreate() failed', dom=self)
libvirt.libvirtError: internal error: process exited while connecting to monitor: 2018-08-20T06:15:00.830835Z qemu-system-x86_64: -drive file=/var/lib/libvirt/images/nixops-0f3af861-a440-11e8-8798-309c233b770e-main.qcow2,format=qcow2,if=none,id=drive-ide0-0-0: Could not open '/var/lib/libvirt/images/nixops-0f3af861-a440-11e8-8798-309c233b770e-main.qcow2': Permission denied